---

- name: build the sending email environment
  hosts: localhost
  become: true
  become_method: sudo

  vars:
    mailsvr: "mail-svr"
    mailsvr_port: 25
    smtp_svr: "smtp.bar.com"
    smtp_usr: "alan"
    smtp_pwd: "alan123"
    mailsvr_image: "catatnight/postfix"
    to_email: ""
    app_source: "/home/caozy/agiler-microservice/sendmail/app"
    container_app_source: "/app"
    sendmailsvr: "test-send-email"
    
  tasks:
  - name: build postfix container
    docker_container:
      name: "{{ mailsvr }}"
      image: "{{ mailsvr_image }}"
      state: started
      exposed:
      - "{{ mailsvr_port }}"
      env: 
        maildomain: "{{ smtp_svr }}"
        smtp_user: "{{ smtp_usr }}:{{ smtp_pwd }}"

  - name: apply setting to file
    template:
      src: "{{ app_source }}/index.js.template"
      dest: "{{ app_source }}/index.js"
      
  - name: build test node app
    docker_container:
      name: "{{ sendmailsvr }}"
      image: "node:6.10.3"
      volumes:
      - "{{ app_source }}:{{ container_app_source }}"
      entrypoint: "node {{ container_app_source }}/index.js"
      links:
      - "{{ mailsvr }}:{{ mailsvr }}"
      state: started
      recreate: yes
...